### ISSUE TITLE
Missing "newton_wrap.cs" in "NewtonUnityPlugin\NewtonPlugin"

### ISSUE THREAD

**Issue by SnakeBox** [svenberra/NewtonUnityPlugin#1]
the files should be located in "NewtonUnityPlugin\NewtonPlugin"

**Comment by svenberra** [comment]
newton_wrap.cs will be generated by swig when you build the solution.

**Comment by SnakeBox** [comment]
You right. I had spaces in my folder names that the project was placed in so I got errors. Thanks for the help. Keep the good work up
