### ISSUE TITLE
How can a rigidbody collision with a deformable shape?

### ISSUE THREAD

**Issue by CharlesQHappy** [svenberra/NewtonUnityPlugin#11]
I have an object A which has animation to change its shape,and a newtonbody  B ,which want to collide with A.How can i achieve this?

**Comment by svenberra** [comment]
The only way I could think of is creating a compound collider matching your animated shape and then each frame update the subcolliders transforms according to the animation keyframes. Unfortunately the Unityplugin doesn't expose modifying subcolliders of a compound yet.
That would be the functions NewtonCompoundCollisionGetFirstNode, NewtonCompoundCollisionGetNextNode, NewtonCompoundCollisionSetSubCollisionMatrix etc.

**Comment by CharlesQHappy** [comment]
Thanks very much for your reply,i almost think never gonner receive message from you guys. i will close this issue since there is another similar issue post by me.
