### ISSUE TITLE
NewtonPhysicsWithUnity to Create guidewire!

### ISSUE THREAD

**Issue by CharlesQHappy** [svenberra/NewtonUnityPlugin#12]
BUT i'm tring to make the treecollider dynamic(not static)，and make it collide with the guidewire continuously! Unfortunately，the NewtonPhysics CAN NOT surpport dynamic treecollider now.Can you help me with that?

**Comment by svenberra** [comment]
Treecolliders can only be static and is mostly suited for large polygon meshes such as terrain or level geometry. It wouldn't be fast enough to be of any use if it was dynamic and it may also be impossible to calculate a volume from a terrain. If you want a concave mesh to be dynamic you could create a compound collider using "Approximate Convex Decomposition". Newton has this functionality but we haven't implemented that in the plugin.
http://www.newtondynamics.com/wiki/index.php/NewtonMeshApproximateConvexDecomposition

**Comment by CharlesQHappy** [comment]
I've thought of 3ways. Please help me see if it's feasible.
1. The first way is the same as you said. But there are not support in the plugin.
2. There seems to be "deformermeshcollision.cpp" in the source code. I wonder if this file is just to achieve the collision of deformable objects.
3. I write the collision detection part myself, and use the output of collision detection as the input of the collision processing system of Newton Physics. But I couldn't find the specific part of collision handling.

As for the fact that some interfaces of Unity are not open, may I venture to ask if you are one of the authors? Can you help me achieve this function? I can pay for that. And it can be made public to more people, which is also good for Newton Physics.

In addition, I have received an email reminding me that my Newton Physics forum account has been activated, but when I log in, I am reminded that my account does not exist. My account number is: charles. Yu

**Comment by CharlesQHappy** [comment]
NewtonPhysics is outstanding , i love itsderterministic solver,it can do what the giant can not, i will try it a lot with unity. One of out product  is depending on NewtonPhysics too and it works well,dynamic collision of deformable mesh is the last step !So please plesae add that function, it's just great!

**Comment by svenberra** [comment]
I just wrote the Unity plugin with alot of help from Julio Jerez(The author of NewtonDynamics). I'm not sure of the status of deformable shapes in Newton. I believe Julio mentioned he was working on soft bodies but I think that is still a work in progress. You could ask on the forum but I guess your account haven't been activated yet. I've sent a pm to Julio and asked him to check the status of your account.

**Comment by CharlesQHappy** [comment]
Glad to hear that,thoung it maybe a WIP. Could you tell him what i want by the way? I am somehow in a hurry to konw the anwser and Julio Jerez seems busy casue he didn't reply very ofen.Thanks for your great work again! it helps a lot!

**Comment by CharlesQHappy** [comment]
And i just found the Newton do have softbody function from the forum! even in 2017! Great news!

**Comment by CharlesQHappy** [comment]
I can pay 1000 dollors for the continous collision detection and handling of deformable object in Unity. It should be point out that i do not need all the functions of softbody but only what i mentioned. However, I know this work maybe a lot and what i pay possibly not equal to the work. But that function dose matter in realistic physics simulation. And its an advantage for physics engines. Would you please try that? There just too little information from the author  or the documents for me to do annything./(ㄒoㄒ)/~~

**Comment by svenberra** [comment]
Well, i haven't tried softbodies at all in Newton but i'm pretty sure it's still a WIP. CCD might work but the last I heard of it it was having some issues as well. But instead of CCD you could try making 2 substeps instead. It will make the simulation slightly slower but much more accurate and reduce the risk of tunneling.

**Comment by CharlesQHappy** [comment]
thanks for your reply! i came to another way: i can do the collision detection part  and send the result to Newton‘s collision detection. If only can you intergrate the interface of the collision handli! how is that?

**Comment by svenberra** [comment]
I suppose you are talking about the usercollision in Newton there Newton gives the AABB to check and you return a list of triangles to test collision against. Don't want to be a drag but there is one big problem with making native plugins for Unity. Multithreading and thread safety. Callbacks made from Newton will happen from other threads and these callbacks cannot access a gameobject in Unity. We had to work around this by handling the callbacks on the c++ side and user iterators on the main thread to query the results. One thing I haven't solved for example is to handle contact processing and I still haven't found any good solution to this. This cannot be done post update but need to happen during the integration step of the simulation.  Unfortunately usercollision callbacks would suffer the same problem with multithreading. So fetching transforms and contacts can be done post update on the main thread but contact processing(add contacts, remove contacts, adjust friction etc) and custom collision detection cannot. I myself haven't used Unity for a long time so maybe things have changed but I guess this limitation still applies. I read about something called ECS in Unity but I don't know much about this or if it could be used to solve these issues or not.
