### ISSUE TITLE
Can you share how you make this plugin?

### ISSUE THREAD

**Issue by CharlesQHappy** [svenberra/NewtonUnityPlugin#16]
The newton is great! I want to intergrate it  into unity deeply.  I see you have stopped to do this project now. Could you share your method and experience?

**Comment by TrevorCash** [comment]
Hi charlesyulife,

In general as a method I made seperate game object components for collision shapes and rigid bodies.  maintaining that multiple collision shape components can be added to a single rigid body for compound collisions.  there is a more official unity newton plugin already out there.  you can check the newton forums.
