### ISSUE TITLE
Demo Scenes loose script references

### ISSUE THREAD

**Issue by Welborn09** [svenberra/NewtonUnityPlugin#3]
I was able to compile the needed sdk and have them now in the demo Unity project. But when I open up a scene (demo_01_BasicCollisionPrimives for instance) and click on a gameObject none of the scripts are there and I am forced to provide them again. However, with me not being familiar enough with this sdk I am not sure which scripts to attach to the objects. I am assuming NewtonBody and maybe a NewtonCollider, but there is more to this I am sure. 

Can you provide some direction on what would typically go into these objects? I did try googling for this hoping someone made a youtube tutorial but no luck.

thanks.

**Comment by Welborn09** [comment]
I wanted to update this by saying I was able to get a few of the scenes working using good ole common sense. If it's a box collider obviously I would use the NewtonBoxCollider and so on. 

The scripts were lost because I upgraded the project to 2017.2 which I forgot does that.

Thanks for the work.

**Comment by svenberra** [comment]
Glad you solved it yourself. I will find some time to upgrade to Unity 2017.2 and update the demo projects.
