### ISSUE TITLE
Trouble compiling NewtonUnityPlugin

### ISSUE THREAD

**Issue by yoonjoonso** [svenberra/NewtonUnityPlugin#4]
Hello, I'm have trouble compiling NewtonUnityPlugin solution.
I think it may have to do with Environment Variables, I'm not sure if I'm pointing at the right place.
I have it now like
NEWTON_DYNAMICS
C:\Physics\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64

The compiler gives me things like "Cannot find dMathConstant.h" which leads to SWIG problems I think.

**Comment by svenberra** [comment]
The environment variable should point to the root of where Newton is, so in your case it should be C:\Physics\newton-dynamics-master
