### ISSUE TITLE
Remove hinge

### ISSUE THREAD

**Issue by adrianp91** [svenberra/NewtonUnityPlugin#5]
Hi!
How can i remove hinges? or joints? in runtime of course.
Destroying hinge components does not work.
Do i need to copy those c# scripts with Newton classes to my project or i just can use only compiled dll's?
Thanks!

**Comment by svenberra** [comment]
Hi.
I've updated the plugin to destroy the joint immediately when a joint component is removed, please try again.

You don't need to copy the c# scripts, they are compiled and copied into the folder Demos/Assets/Plugins folder when you build the solution.
So if creating a new Unity project from scratch, it should be enough to copy those plugins(NewtonPlugin.dll, NewtonWrapper.dll) and also NewtonPluginEditor.dll from demos/assets/Editor

**Comment by adrianp91** [comment]
Awesome! Thanks!
