### ISSUE TITLE
Am I now available to compile this plugin for mobile platforms?

### ISSUE THREAD

**Issue by CIVITAS-John** [svenberra/NewtonUnityPlugin#6]
As the title :)

If it's possible it will be most kind of you to guide a path that I may finish it myself; otherwise please stop me doing so before wasting too much time..

**Comment by svenberra** [comment]
Nope. Still only Windows. Personally i'm not interested in mobile development so it's nothing i've prioritized.
I'm sure it can be done but i wouldnt be much help.
