### ISSUE TITLE
Can't build with current version of Newton Dynamics

### ISSUE THREAD

**Issue by HiceS** [svenberra/NewtonUnityPlugin#7]
Finally got it to semi-compile after making the path absolute for the repo after cloning and running VS in administrative mode.

<img width="1440" alt="screen shot 2018-08-15 at 1 57 06 pm" src="https://user-images.githubusercontent.com/6741771/44172901-51559500-a093-11e8-9a32-e8ad1d658f99.png">

' 

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | C2664 | 'void NewtonMaterialSetCompoundCollisionCallback(const NewtonWorld *const ,int,int,NewtonOnCompoundSubCollisionAABBOverlap)': cannot convert argument 4 from 'int (__cdecl *)(const NewtonMaterial *const ,const NewtonBody *const ,const void *const ,const NewtonBody *const ,const void *const ,int)' to 'NewtonOnCompoundSubCollisionAABBOverlap' | NewtonWrapper | c:\newtonunityplugin\newtonwrapper\wrappersdk\dnewtonworld.cpp | 64 |  
 '

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error (active) | E0167 | argument of type "int (*)(const NewtonMaterial *material, const NewtonBody *body0, const void *collisionNode0, const NewtonBody *body1, const void *collisionNode1, int threadIndex)" is incompatible with parameter of type "NewtonOnCompoundSubCollisionAABBOverlap" | NewtonWrapper | c:\NewtonUnityPlugin\NewtonWrapper\wrapperSdk\dNewtonWorld.cpp | 64 |  

One of the objects is returning a int instead of a 

`	NEWTON_API void NewtonMaterialSetCompoundCollisionCallback(const NewtonWorld* const newtonWorld, int id0, int id1, int * compoundAabbOverlap);`

`	NEWTON_API void NewtonMaterialSetCompoundCollisionCallback(const NewtonWorld* const newtonWorld, int id0, int id1, NewtonOnCompoundSubCollisionAABBOverlap compoundAabbOverlap);`

`typedef int (*NewtonOnCompoundSubCollisionAABBOverlap) (const NewtonJoint* const contact, dFloat timestep, const NewtonBody* const body0, const void* const collisionNode0, const NewtonBody* const body1, const void* const collisionNode1, int threadIndex);`

The definition of NewtonOnCompoundSubCollisionAABBOverlap appears to still be an int pointer so there is a loss of derivation somewhere.

**Comment by HiceS** [comment]
`typedef int (*NewtonOnCompoundSubCollisionAABBOverlap) (const NewtonJoint* const contact, dFloat timestep, const NewtonBody* const body0, const void* const collisionNode0, const NewtonBody* const body1, const void* const collisionNode1, int threadIndex);`

The definition of NewtonOnCompoundSubCollisionAABBOverlap appears to still be an int pointer so there is a loss of derivation somewhere.

**Comment by svenberra** [comment]
Think there was some breaking changes with compound colliders a while ago. Try using an older Newton revision until I can get it sorted out.

**Comment by svenberra** [comment]
This should be fixed now, closing issue
