### ISSUE TITLE
XCopy Error :VCEND exited with code 4

### ISSUE THREAD

**Issue by mb03minecrafter** [svenberra/NewtonUnityPlugin#8]
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "rem xcopy  "..\PluginBin\NewtonWrapper.dll" "C:\Users\julio\Downloads\Gerador.Newton\Collisions_Data\Plugins/*.*"  /F /Y /R
rem xcopy  "..\PluginBin\NewtonWrapper.pdb" "C:\Users\julio\Downloads\Gerador.Newton\Collisions_Data\Plugins/*.*"  /F /Y /R

xcopy  "..\PluginBin\NewtonWrapper.dll" "../Demos/Assets/Plugins/*.*"  /F /Y /R
xcopy  "..\PluginBin\NewtonWrapper.pdb" "../Demos/Assets/Plugins/*.*"  /F /Y /R

xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx\Release\*.dll" "../PluginBin/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx2\Release\*.dll" "../PluginBin/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonsse4.2\Release\*.dll" "../PluginBin/newtonPlugins/Release/*.*"  /F /Y /R 

xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx\Release\*.dll" "../Demos/Assets/Plugins/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx2\Release\*.dll" "../Demos/Assets/Plugins/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonsse4.2\Release\*.dll" "../Demos/Assets/Plugins/newtonPlugins/Release/*.*"  /F /Y /R 
:VCEnd" exited with code 4.	NewtonWrapper	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133	
`

There it is, I am following the exact directions and this is the only error I get. It seems as if it is trying to use YOUR file path instead of MY file path. Also, I can assure you that my Newton Dynamics Install is clean and the Environment variable is set correctly since I am using the same directory as specified in the ReadME. Hope you can help, thanks!

**Comment by svenberra** [comment]
Hmm strange, I don't get those errors and the the first two xcopy commands are preceded with a rem which should prevent them from executing. But i removed them now since they are some test commands Julio left behind. Try again and see if it works better after I removed those lines.

**Comment by mb03minecrafter** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "xcopy  "..\PluginBin\NewtonWrapper.dll" "../Demos/Assets/Plugins/*.*"  /F /Y /R
xcopy  "..\PluginBin\NewtonWrapper.pdb" "../Demos/Assets/Plugins/*.*"  /F /Y /R

xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx\Release\*.dll" "../PluginBin/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx2\Release\*.dll" "../PluginBin/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonsse4.2\Release\*.dll" "../PluginBin/newtonPlugins/Release/*.*"  /F /Y /R 

xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx\Release\*.dll" "../Demos/Assets/Plugins/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonAvx2\Release\*.dll" "../Demos/Assets/Plugins/newtonPlugins/Release/*.*"  /F /Y /R 
xcopy  "C:\newton-dynamics-master\sdk\projects\visualStudio_2015_static_mt\x64\dgNewtonsse4.2\Release\*.dll" "../Demos/Assets/Plugins/newtonPlugins/Release/*.*"  /F /Y /R 
:VCEnd" exited with code 4.	NewtonWrapper	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133	


So now I get this, seems like it is trying to access libraries that aren't even compiled, as I looked in my newton install directory and it shows that the folders it is trying to access simply don't exist. So it maybe seems like something it wrong with my install directory, but when I compile I simply don't create "dgNewtonAvx" or "dgNewtonAvx2" or "dgNewtonsse4.2"

**Comment by mb03minecrafter** [comment]
Ok, so now after I compile these folders manually in visual studio instead of attempting to compile the entire project, it seems to generate these folders with the proper .dlls. It seems as if it is working now. Thanks.

**Comment by svenberra** [comment]
Great. Odd that you couldn't build the whole solution though.
